git:
    submodules: false

language: php
php:
    - 7.1

before_script:
    - travis_retry composer install --no-interaction --prefer-dist

script:
    - vendor/bin/tester tests/

cache:
    directories:
        - $HOME/.composer/cache

